from sense_hat import SenseHat
sense = SenseHat()
sense.show_message("Los!")
sense.clear()
sense.load_image("s.png")
humidity = sense.get_humidity()
#sense.show_message("Luftfeuchtigkeit: %s %%rH" % humidity)
print("Luftfeuchtigkeit: %s %%rH" % humidity)
temp = sense.get_temperature()
#sense.show_message("Temperatur: %s C" % temp)
print("Temperatur: %s C" % temp)
temp = sense.get_temperature_from_humidity()
#sense.show_message("Temperatur-Feuchtigkeit: %s C" % temp)
print("Temperatur-Feuchtigkeit: %s C" % temp)
temp = sense.get_temperature_from_pressure()
#sense.show_message("Temperatur-Druck: %s C" % temp)
print("Temperatur-Druck: %s C" % temp)
pressure = sense.get_pressure()
#sense.show_message("Druck: %s Millibars" % pressure)
print("Druck: %s Millibars" % pressure)