from sense_hat import SenseHat
sense = SenseHat()
sense.show_message("Los!")
sense.clear()
sense.load_image("s.png")
humidity = sense.get_humidity()
sense.show_message("Humidity: %s %%rH" % humidity)
temp = sense.get_temperature()
sense.show_message("Temperature: %s C" % temp)
temp = sense.get_temperature_from_humidity()
sense.show_message("Temperature-Feuchtigkeit: %s C" % temp)
temp = sense.get_temperature_from_pressure()
sense.show_message("Temperature-Druck: %s C" % temp)
pressure = sense.get_pressure()
sense.show_message("Pressure: %s Millibars" % pressure)
